---
apiversion: v1
kind: Deployment
metadata:
  name: java-test1-deployment
  labels:
    app: java-test2-deployment
spec:
  replicas: 1
  selector:
    matchlabels: app:java-test2-deployment
  template:
    metadata:
      labels:
        app: java-test3-deployment
    spec:
      containers: null
      -name: java-test4
      image: sukhanth/jenkinsfile_jaja_k8s
      ports:
        - containerPort: 8020

---
apiVersion: v1
kind: Service
metadata:
  name: javaservice01
spec:
  selector:
    app: java-test3-deployment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8085
      targetport: 8020
      nodeport: 30000
